Extracted comments and added line comments support
preview-code/code-highlighter pull request #9
Opened 2017-03-28 08:08 UTC by eanker

Together with preview-code/comments#3 and preview-code/frontend#468

2017-03-30 10:10 UTC, txsmith requested changes

2017-03-30 10:10 UTC, txsmith commented on bower.json
> +    "util": "preview-code/util"
Should some of these not be dev-dependencies?

2017-03-30 10:10 UTC, txsmith commented on bower.json
> +    "util": "preview-code/util"
I believe markdown-input is unnecessary

2017-03-30 10:10 UTC, txsmith commented on test/code-highlighter.html
>            assert.equal(e.detail.lines, elem._amountLines);
Forgot to remove this assert

2017-03-30 10:10 UTC, txsmith commented on bower.json
> +    "util": "preview-code/util"
We should also increase the version number according to semver

2017-03-30 10:10 UTC, txsmith commented on code-with-comment.html
> +    <add-comment on-add-comment="addComment" hidden="{{hideAddComments}}" project="[[project]]" line-comment="true"></add-comment>
`hidden="{{hideAddComments}}"` -> `hidden=$"{{hideAddComments}}"`

2017-03-30 10:10 UTC, txsmith commented on code-with-comment.html
> +    <code-highlighter code="{{code}}" before-start="{{beforeStart}}" after-start="{{afterStart}}" can-split="true" amount-lines="{{amountLines}}"></code-highlighter>
`amountLines` should not be set here since it is computed in `code-highlighter`

2017-03-30 10:10 UTC, txsmith commented on code-highlighter.html
> +        },
Perhaps we should make this property `readOnly`

2017-03-30 10:10 UTC, txsmith commented on code-with-comment.html
> +        amountLines: Number
This property is not needed since we can retrieve it from `code-highlighter`

2017-03-30 10:10 UTC, txsmith commented on code-with-comment.html
> +        user: Object,
Do we need the user here? It seems like this dependency can be avoided.

2017-03-30 10:10 UTC, txsmith commented on code-with-comment.html
> +          newChunk.afterStart = this.afterStart;
In my opinion, this would be more beautiful:
```
var newChunk = {
  startLine = this.startLine;
  beforeStart = this.beforeStart;
  afterStart = this.afterStart;
};
```
\</nitpick>

2017-03-30 10:10 UTC, txsmith commented on hunk-element.html
>        }
There are unused imports at the top of this file.

2017-03-30 10:10 UTC, txsmith commented on hunk-element.html
> +        comments="{{item.comments}}" index-item="[[item.index]]" hide-comments="[[hideComments]]" start-line="{{item.startLine}}"
`index-item` was removed right?

2017-03-30 10:10 UTC, txsmith commented on hunk-element.html
> +      observers: ['_getChunks(hunk.*)'],
This could use a better name: `_onHunkChange`

2017-03-30 10:10 UTC, txsmith commented on hunk-element.html
> +        chunks: {
I think `chunks` should be prefixed with an `_`

2017-03-30 10:10 UTC, txsmith commented on hunk-element.html
> +          line.startsWith('+') ? '' : newBeforeStart++;
`if (line.startsWith('+')) newBeforeStart++;`

2017-03-30 11:57 UTC, eanker commented on code-with-comment.html
> +    <code-highlighter code="{{code}}" before-start="{{beforeStart}}" after-start="{{afterStart}}" can-split="true" amount-lines="{{amountLines}}"></code-highlighter>
How can we do this then, so that `amountLines` is updated as it changes in code-highlighter?

2017-03-30 12:00 UTC, eanker commented on code-with-comment.html
> +        user: Object,
The user is needed for the pushing of comments.
I'll look at this in the next pr to include with the callback.

2017-03-30 12:01 UTC, txsmith commented on code-with-comment.html
> +    <code-highlighter code="{{code}}" before-start="{{beforeStart}}" after-start="{{afterStart}}" can-split="true" amount-lines="{{amountLines}}"></code-highlighter>
You can ignore this comment, I thought i had removed it but apparently I did not...

2017-03-30 12:06 UTC, eanker commented on code-with-comment.html
> +    <add-comment on-add-comment="addComment" hidden="{{hideAddComments}}" project="[[project]]" line-comment="true"></add-comment>
`hidden$=` or `hidden=$` does not work properly

2017-04-04 07:09 UTC, txsmith approved these changes

2017-04-04 07:09 UTC, merged